name: Build - CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion:
          - 10
          - 12
          - 14
          - 16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Modules
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Package - Dry run
        run: npm publish --dry-run

      - name: Test
        run: npm run test
